# Generated by Django 3.2 on 2023-07-07 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blogs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(max_length=120)),
                ('post', models.CharField(max_length=250)),
                ('online', models.BooleanField(default=True)),
            ],
        ),
    ]
